### ISSUE TITLE
<BaseLink> props are not transfered to the underlying <a>

### ISSUE THREAD

**Issue by motet-a** [router5/react-router5#34]
If I write:

```js
<BaseLink title="Leaves" 
          routeName="trees.leaves"
          routeParams={{ treeId: "ash" }}>
  Leaves
</BaseLink>
```

In the rendered HTML, the `title` attribute is not set on the underlying `<a>` element:

```js
<a href="/trees/ash/leaves">
  Leaves
</a>
```

It would be convenient to transfer every prop to the `<a>` element (except `activeClassName`, `routeName`, `routeParam` and so on).

I can submit a PR (tests included :battery:).

Thanks.

**Comment by troch** [comment]
v4.2.0 now supports `title`. I've looked into other hyperlink attributes, and apart from `hrefLang` I couldn't see the benefit of supporting more for now.

**Comment by motet-a** [comment]
Thanks! In fact, [react-router does this](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L65).

**Comment by troch** [comment]
That's what I wanted to do initially, but `BaseLink` takes a lot more props, some of which are not consumed in the render function. I would have had to destructure all of them before being able to group "other" props. Since there are actually very little hyperlink attributes one might be interested in (for example stuff like `rel` and `target` wouldn't be use for a link internal to your app), it's easier to list supported attributes.

**Comment by motet-a** [comment]
Another solution is to use an intermediate prop:

```js
<BaseLink aProps={{ title: 'Leaves' }}
          routeName="trees.leaves"
          routeParams={{ treeId: "ash" }}>
  Leaves
</BaseLink>
```

↓

```html
<a href="/trees/ash/leaves"
   title="Leaves">
  Leaves
</a>
```

However, it’s not really pretty.

**Comment by motet-a** [comment]
Note it could be useful to allow to use event handler like `onMouseEnter`, `onContextMenu` and so on.

**Comment by troch** [comment]
@motet-a finally did this, now any prop can be passed to the link component, and it will be passed to its hyperlink element (see router5/router5#201)

**Comment by motet-a** [comment]
Thanks!
