### ISSUE TITLE
How do I combine multiple routeNodes?

### ISSUE THREAD

**Issue by cyberhck** [router5/react-router5#37]
I'm creating routes on a separate files like `MessagesRoute` and `UsersRoute`.

There, I'm exporting `routeNode('messages')` & `routeNode('users')`

Now when I render both`<MessagesRoute />` and `<UsersRoute />` both of them are activated and even though one matches, other one shows `Not Found` page.

Is there a way to combine those two nodes? Is there a project (Not example project) using this router?

TIA.

**Comment by troch** [comment]
Hi, can you show me some code? React example is here: https://github.com/router5/examples/tree/master/apps/react

**Comment by cyberhck** [comment]
@troch thanks for instant reply, here's a POC I wanted to do: https://github.com/cyberhck/router5-poc/tree/e8e80b1672d71669e4099808f9f4fe1e72e2547e

There in `src/Routes/ProductRoutes.tsx` and ``src/Routes/UserRoutes.tsx` I've defined component for routing, but both of them are rendered in `src/App.tsx`, is there something like combine nodes?

edit:
I tried to combine both into a single `src/Routes/Routes.tsx` file and it starts working normally, then I've one more issue where I can't get my browser's back and forward button to work properly, routes changes, but view isn't rendered, even though I'm using `browserPlugin`

**Comment by troch** [comment]
I assume you don't want to repeat `/users` and `/products` in edit URLs.

```diff
export default [
    {name: 'users', path: '/users'},
-    {name: 'users.edit', path: '/users/edit'},
+    {name: 'users.edit', path: '/edit'},
    {name: 'products', path: '/products'},
    {name: 'products.edit', path: '/products/edit'}
-    {name: 'products.edit', path: '/products/edit'}
+    {name: 'products.edit', path: '/edit'} 
];
```

The only reason for nesting routes is not nested URLs, but nested components. `routeNode` works for nested routes and avoids re-rendering of parts of your UI which are not concerned by a route change, and is used instead of `withRoute` (which re-render its wrapped component on every single route change).

Your components are not properly connected: `App` needs to be connected to node `''`, `ProductRoutes` needs to be connected to node `'product'`, etc...

I would encourage you to start with flat routes, use `withRoute` and as your app grows, start to make optimisations with `routeNode` and nested routes.

**Comment by cyberhck** [comment]
Okay, I made a some changes, basically for now, `ProductRoutes` and `UsersRoutes` merged to `Routes`, https://github.com/cyberhck/router5-poc/tree/e2c48064430521203a40d659e6c6b102ea96c8c6 and `App` connected to "", (I also tried without connecting), and now the navigation is broken (even when I click on link on `/users` page, it doesn't actually render anything.

But if I manually go to the URL it renders,

**Comment by cyberhck** [comment]
@troch is it required to render inside `router.start()` method? or is it also possible to render just before calling `router.start()`?

**Comment by troch** [comment]
It doesn't matter, inside or outside.

**Comment by cyberhck** [comment]
@troch thanks :) now it's working perfectly, `canDeactivate` and `canActivate` handlers are also working great, https://github.com/cyberhck/router5-poc/tree/0.0.1 is a good starting point for someone new to this repo and want to use with TypeScript. Will try router5-redux in a while.
